### ISSUE TITLE
Suggestion: Special treatment for unsecured JWTs ("alg": "none")

### ISSUE THREAD

**Issue by mkauf** [babelouest/rhonabwy#11]
The [cjose library](https://github.com/cisco/cjose) always reports that tokens with `"alg": "none"` are invalid, because of the security problems with `"alg": "none"`. See [Critical vulnerabilities in JSON Web Token libraries](https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/#Meet-the--None--Algorithm).

So maybe Rhonabwy could do the same?

**Comment by babelouest** [comment]
Thanks for this, it raised me some questions about the implementation.

I agree using tokens with `alg: "none"` may be useless, but it could be useful sometimes.
Like when an OAuth2 request parameter is sent by a public client in a JWT format, the client has no secret or secret key to sign the message. In that case, a non signed token is useful.
https://datatracker.ietf.org/doc/html/rfc7523

Nevertheless, the signature verification must not return `RHN_OK` if the token is not signed, I'll fix that soon.

**Comment by babelouest** [comment]
@mkauf , I'm also open to suggestions and feedbacks about that, maybe my interpretation above is not completely accurate. Do you have ideas of improvements concerning the `alg: "none"`?

**Comment by babelouest** [comment]
An first update has been committed here: https://github.com/babelouest/rhonabwy/commit/ff9ecad4c9a031c8369acde67ea52d558899e51e , but I'll wait for your feedback before closing this issue.

**Comment by mkauf** [comment]
I agree that ``r_jws_verify_signature()`` should return an error code for  ``"alg": "none"``.

I don't know whether the use case with OAuth2 that you mentioned is still possible with these changes, though. Would a special error code help, e. g. ``RHN_ERROR_UNSECURED`` ?

**Comment by babelouest** [comment]
> I don't know whether the use case with OAuth2 that you mentioned is still possible with these changes

An example of `alg:"none"` I talk about is here: https://github.com/babelouest/glewlwyd/blob/master/src/plugin/protocol_oidc.c#L4283

If the client is confidential, the algorithm used must match type allowed for the client. If the client is public, the algorithm must be `none`.

The functions I see where the algorithm should be checked are:
- [r_jws_parse](https://babelouest.github.io/rhonabwy/group__jws.html#gae1b043a46071322f988c8d714883a208) and its derivations, including jwt
- [r_jws_serialize](https://babelouest.github.io/rhonabwy/group__jws.html#gaaca013bc2c9c3fe1e85386187504b235) and its derivations, including jwt

Instead of adding an error value `RHN_ERROR_UNSECURED`, I have another suggestion:
- change the behavior of `r_jws_parse` et al to return `RHN_ERROR_INVALID` when a token with `alg:"none"` is parsed
- change the behavior of `r_jws_serialize` et al to return NULL if `alg:"none"` is used
- add functions `r_jws_parse_unsecure` and `r_jws_serialize_unsecure` et al, they will be the only one allowed to manage `alg:"none"` signed tokens

**Comment by mkauf** [comment]
I'm fine with the proposed changes. It's a good approach to make it explicit whether unsecured tokens are allowed.

This issue can be closed, commit ff9ecad is already sufficient for my use case.

**Comment by babelouest** [comment]
@mkauf , I've made the changes in the master branch, the API documentation has been updated too:

- [Unsecured JWS](https://github.com/babelouest/rhonabwy/blob/master/API.md#unsecured-jws)
- [Unsecured JWT](https://github.com/babelouest/rhonabwy/blob/master/API.md#unsecured-jwt)

Can you verify that those changes don't break your tests?

**Comment by mkauf** [comment]
I have tested with the master branch, it runs well and our tests have succeeded. Thanks a lot!
