### ISSUE TITLE
[FeatureReq] Support for Windows

### ISSUE THREAD

**Issue by PataviniMa** [babelouest/rhonabwy#19]
Hello,
can this library be built on Windows (with MinGW an CMake, for example)?

**Comment by babelouest** [comment]
Hello,

I believe you can, I just don't know how precisely.

It's already available in [YACP](https://github.com/fd00/yacp/tree/master/rhonabwy), and I've been told all the dependencies can be built on windows.
Also, someone described [how to build ulfius with CMake and Visual Studio 2019](https://github.com/babelouest/ulfius/issues/111) which has similar dependencies than rhonabwy.

If you manage to build rhonabwy for windows, I'd love to improve the install documentation to describe how, because I think it will be helpful for others.

**Comment by babelouest** [comment]
@PataviniMa , were you able to build and/or use rhonabwy for Windows with the tips I gave you?

**Comment by babelouest** [comment]
I suggest to continue this question in the [discussion thread](https://github.com/babelouest/rhonabwy/discussions/5) with the same topic of needed.

**Comment by sfhacker** [comment]
Any updates/progress here?
