### ISSUE TITLE
validating array values

### ISSUE THREAD

**Issue by spaceone** [babelouest/rhonabwy#34]
Hello,

I have a audience claim, which is a list (generated by Keycloak):
```
"aud": [
    "ldaps://school.dev/",
    "account"
  ],
```

`r_jwt_validate_claims(jwt, R_JWT_CLAIM_AUD, "ldaps://school.dev/", R_JWT_CLAIM_NOP)` doesn't return `RHN_OK`.
and `r_jwt_get_claim_str_value(jwt, "aud")` returns `NULL`.

What can I do, to validate this correctly?

**Comment by babelouest** [comment]
Hello @spaceone ,

Thanks for the issue, the problem is not in your code but in my interpretation of the [specification](https://openid.net/specs/openid-connect-basic-1_0.html#IDToken) which was wrong.

Ive fixed the aud claim check so it can be a string or an array of strings, can you test with the [last commit](https://github.com/babelouest/rhonabwy/commit/c89de3327785c0ab9fcb0a48a002e3ed48b66ecb)?

**Comment by spaceone** [comment]
Thank you, that worked.
